"""empty message

Revision ID: c884d6192324
Revises: 
Create Date: 2023-02-11 20:10:46.488706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c884d6192324'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('file_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('desc', sa.String(length=1000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('desc')
        batch_op.drop_column('file_name')
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
